title: Virgínia Fernandes Mota
description: Professora do COLTEC — UFMG, pesquisadora em acessibilidade em jogos digitais e visão computacional
baseurl: "/" # ou "/" se for o repositório username.github.io
url: "https://virginiamota.github.io"
theme: minima
